apiVersion: v1
kind: Service
metadata:
  name: database-service

spec:

  selector:
    app: db

  ports:
    - name: http
      port: 3306
      nodePort: 31002
      

  type: NodePort