apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: samarth-deployment
spec:
  
  replicas: 3
  template: # template for the pods
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: helloimage
        image: sam0157/nodeimage:latest
        ports:
        - name: hello-port
          containerPort: 3000