apiVersion: v1
kind: Service
metadata:
  name: samarth-service

spec:

  selector:
    app: hello

  ports:
    - name: http
      port: 31002
      nodePort: 31001
      targetPort: hello-port

  type: NodePort