apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: samarth-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: k8s-demo
        image: sam0157/nodeimage:v4
        ports:
        - name: app-port
          containerPort: 3000
        volumeMounts:
        - name: cred-volume
          mountPath: /etc/creds
          readOnly: true
      volumes:
      - name: cred-volume
        secret:
          secretName: db-secrets